# Generated by Django 2.1.2 on 2018-11-18 12:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clan_name', models.CharField(max_length=255)),
                ('clan_tag', models.CharField(max_length=5)),
                ('clan_agenda', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('psn_id', models.CharField(blank=True, max_length=30)),
                ('belong_clan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.Clan')),
            ],
        ),
    ]
