# Generated by Django 2.1.2 on 2018-11-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='belong_clan_authority',
            field=models.IntegerField(choices=[(1, 'Master'), (2, 'Sub Master'), (3, 'Member')], default=1),
        ),
    ]
